#!/usr/bin/env python
from __future__ import print_function
from states import *
import states.helpers as helpers
import argparse
import os
from version import __version__


def backup(args):
    args.filename = set_backup_filename(args)
    if args.state:
        # state already exists, no need to pull from remote
        args.filename = args.state
    else:
        save_remote_state_to_local(args)
    upload_to_s3(args)


def init(args):
    save_remote_state_to_local(args)


def pull(args):
    r, l = RemoteState(args.profile), LocalState(args.filename)
    diff = helpers.FlatDictDiffer(r.get(paths=args.path), l.get(paths=args.path))
    state = get_pull_state(diff, args.force)
    l.save(helpers.unflatten(state))


def apply(args):
    r, _, diff = plan(args)
    print("\nApplying changes...")
    try:
        r.apply(diff)
        print("Done.")
    except Exception as e:
        print("Failed to apply changes to remote:", e)


def plan(args):
    r, l = RemoteState(args.profile), LocalState(args.filename)
    diff = helpers.FlatDictDiffer(r.get(paths=args.path), l.get(paths=args.path))
    print_plan_result(diff)
    return r, l, diff


def set_backup_filename(args):
    return helpers.timestamp() + '.yml' if args.filename == 'parameters.yml' else args.filename


def save_remote_state_to_local(args):
    r, l = RemoteState(args.profile), LocalState(args.filename)
    l.save(r.get(flat=False, paths=args.path))


def upload_to_s3(args):
    s3 = S3State(args.bucket, args.key, args.profile, args.filename)
    s3.save()


def get_pull_state(diff, force):
    dictfilter = lambda x, y: dict([(i, x[i]) for i in x if i in set(y)])
    if force:
        ref_set = diff.changed().union(diff.removed()).union(diff.unchanged())
        target_set = diff.added()
    else:
        ref_set = diff.unchanged().union(diff.removed())
        target_set = diff.added().union(diff.changed())
    state = dictfilter(diff.ref, ref_set)
    state.update(dictfilter(diff.target, target_set))
    return state


def print_plan_result(diff):
    if diff.differ:
        diff.print_state()
    else:
        print("Remote state is up to date.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--version', '-v', action='version', version='%(prog)s ' + __version__)
    parser.add_argument('-f', help='local state yml file', action='store', dest='filename', default='parameters.yml')
    parser.add_argument('--path', '-p', action='append', help='filter SSM path')
    parser.add_argument('--profile', help='AWS profile name', action='store', dest='profile')
    subparsers = parser.add_subparsers(dest='func', help='commands')
    subparsers.required = True

    parser_backup = subparsers.add_parser('backup', help='backup remote state to s3 bucket')
    parser_backup.set_defaults(func=backup)
    parser_backup.add_argument('--bucket', help='s3 bucket name', action='store', dest='bucket')
    parser_backup.add_argument('--key', help='s3 key name', action='store', dest='key')
    parser_backup.add_argument('--local-state', help='for the pre-existing local state yml file', action='store',
                               dest='state')

    parser_plan = subparsers.add_parser('plan', help='display changes between local and remote states')
    parser_plan.set_defaults(func=plan)

    parser_init = subparsers.add_parser('init', help='create or overwrite local state snapshot')
    parser_init.set_defaults(func=init)

    parser_pull = subparsers.add_parser('pull', help='pull updates from remote state')
    parser_pull.set_defaults(func=pull)
    parser_pull.add_argument('--force', help='overwrite local changes', action='store_true', dest='force')

    parser_apply = subparsers.add_parser('apply', help='apply diff to the remote state')
    parser_apply.set_defaults(func=apply)

    args = parser.parse_args()
    args.path = args.path if args.path else ['/']

    if args.filename == 'parameters.yml':
        if not args.profile:
            if 'AWS_PROFILE' in os.environ:
                args.filename = os.environ['AWS_PROFILE'] + '.yml'
        else:
            args.filename = args.profile + '.yml'
    args.func(args)
